# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.cache/wt [current_project]
set_property parent.project_path E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo_ooc.xdc]
set_property is_locked true [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1 -new_name audio_fifo -ip [get_ips audio_fifo]]

if { $cached_ip eq {} } {

synth_design -top audio_fifo -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix audio_fifo_ audio_fifo.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ audio_fifo_stub.v
 lappend ipCachedFiles audio_fifo_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ audio_fifo_stub.vhdl
 lappend ipCachedFiles audio_fifo_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ audio_fifo_sim_netlist.v
 lappend ipCachedFiles audio_fifo_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ audio_fifo_sim_netlist.vhdl
 lappend ipCachedFiles audio_fifo_sim_netlist.vhdl

 config_ip_cache -add -dcp audio_fifo.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips audio_fifo]
}

rename_ref -prefix_all audio_fifo_

write_checkpoint -force -noxdef audio_fifo.dcp

catch { report_utilization -file audio_fifo_utilization_synth.rpt -pb audio_fifo_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.v -of_objects [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

add_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.vhdl -of_objects [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

add_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.v -of_objects [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

add_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.vhdl -of_objects [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

add_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo.dcp -of_objects [get_files e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

if {[file isdir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo]} {
  catch { 
    file copy -force E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.v E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo
  }
}

if {[file isdir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo]} {
  catch { 
    file copy -force E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_sim_netlist.vhdl E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo
  }
}

if {[file isdir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo]} {
  catch { 
    file copy -force E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.v E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo
  }
}

if {[file isdir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo]} {
  catch { 
    file copy -force E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.runs/audio_fifo_synth_1/audio_fifo_stub.vhdl E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.ip_user_files/ip/audio_fifo
  }
}
