# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.cache/wt [current_project]
set_property parent.project_path E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/new/UDA1380_Controller.vhd
read_vhdl -vhdl2008 -library xil_defaultlib {
  E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/new/I2C_Controller.vhd
  E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/new/audio_i2s_artix.vhd
}
read_ip -quiet E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo_ooc.xdc]
set_property is_locked true [get_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/sources_1/ip/audio_fifo/audio_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files E:/Facultate_Master/master_arbeit/vivado_projects/audio_i2s_artix/audio_i2s_artix.srcs/constrs_1/new/constraints.xdc]


synth_design -top audio_i2s_artix -part xc7a35tcpg236-1


write_checkpoint -force -noxdef audio_i2s_artix.dcp

catch { report_utilization -file audio_i2s_artix_utilization_synth.rpt -pb audio_i2s_artix_utilization_synth.pb }
